### ISSUE TITLE
runtime: failed to create new OS thread (have 101 already; errno=11)

### ISSUE THREAD

**Issue by shaorui0** [intel/observability-telegraf#2]
Hi, some errors occurred during enable telegraf.

Here are some log messages:
```
2022-05-25T17:54:25Z I! Starting Telegraf 1.19.3
2022-05-25T17:54:25Z I! Using config file: /etc/telegraf/telegraf.conf
2022-05-25T17:54:25Z I! Loaded inputs: cpu intel_powerstat
2022-05-25T17:54:25Z I! Loaded aggregators: 
2022-05-25T17:54:25Z I! Loaded processors: 
2022-05-25T17:54:25Z I! Loaded outputs: influxdb_v2
2022-05-25T17:54:25Z I! Tags enabled: host=telegraf-intel
2022-05-25T17:54:25Z I! [agent] Config: Interval:5s, Quiet:false, Hostname:"telegraf-intel", Flush Interval:5s
runtime: failed to create new OS thread (have 101 already; errno=11)
runtime: may need to increase max user processes (ulimit -u)
fatal error: newosproc

runtime stack:
runtime.throw(0x4f21b0b, 0x9)
        /usr/local/go/src/runtime/panic.go:1117 +0x72
runtime.newosproc(0xc001437c00)
        /usr/local/go/src/runtime/os_linux.go:160 +0x1be
runtime.newm1(0xc001437c00)
        /usr/local/go/src/runtime/proc.go:2144 +0xdd
runtime.newm(0x0, 0xc0000d1000, 0x64)
        /usr/local/go/src/runtime/proc.go:2123 +0xa6
runtime.startm(0xc0000d1000, 0x446400)
        /usr/local/go/src/runtime/proc.go:2378 +0xe5
runtime.handoffp(0xc0000d1000)
        /usr/local/go/src/runtime/proc.go:2412 +0x65
runtime.retake(0x51c4562fd443, 0xc000000006)
        /usr/local/go/src/runtime/proc.go:5366 +0x17d
runtime.sysmon()
        /usr/local/go/src/runtime/proc.go:5274 +0x185
runtime.mstart1()
        /usr/local/go/src/runtime/proc.go:1306 +0xc8
runtime.mstart()
        /usr/local/go/src/runtime/proc.go:1272 +0x6e

goroutine 1 [semacquire, 1 minutes]:
sync.runtime_Semacquire(0xc001175c78)
        /usr/local/go/src/runtime/sema.go:56 +0x45
sync.(*WaitGroup).Wait(0xc001175c70)
        /usr/local/go/src/sync/waitgroup.go:130 +0x65
github.com/influxdata/telegraf/agent.(*Agent).Run(0xc001102048, 0x5936d88, 0xc0010c8540, 0x1, 0x1)
```
telegraf.conf
```
[agent]
  interval = "5s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_interval = "5s"
  flush_jitter = "0s"
  precision = ""
  debug = false
  quiet = false
  logfile = ""
  hostname = "$HOSTNAME"
  omit_hostname = false

# Intel PowerStat plugin enables monitoring of platform metrics (power, TDP) and per-CPU metrics like temperature, power and utilization.
[[inputs.intel_powerstat]]
  ## All global metrics are always collected by Intel PowerStat plugin.
  ## User can choose which per-CPU metrics are monitored by the plugin in cpu_metrics array.
  ## Empty array means no per-CPU specific metrics will be collected by the plugin - in this case only platform level
  ## telemetry will be exposed by Intel PowerStat plugin.
  ## Supported options:
  ## "cpu_frequency", "cpu_busy_frequency", "cpu_temperature", "cpu_c1_state_residency", "cpu_c6_state_residency", "cpu_busy_cycles"
  cpu_metrics = ["cpu_c1_state_residency", "cpu_c6_state_residency", "cpu_busy_cycles"]

# Read metrics about cpu usage
[[inputs.cpu]]
  ## Whether to report per-cpu stats or not
  percpu = true
  ## Whether to report total system cpu stats or not
  totalcpu = true
  ## If true, collect raw CPU time metrics
  collect_cpu_time = true
  ## If true, compute and report the sum of all non-idle CPU states
  report_active = true

[[outputs.influxdb_v2]]
 ...

```
Kernel info
```
Operating System: Ubuntu Jammy Jellyfish (development branch)
Kernel: Linux 5.15.0-1003-realtime
Architecture: x86-64
Hardware Vendor: Intel Corporation
Hardware Model: M50CYP2SBSTD```
```

**Comment by pduzinki** [comment]
When you create the container via _telegraf-intel-docker.sh_ command like _build-run_, the PID limit is set to 100 (**line 67** in _telegraf-intel-docker.sh_. In a scenario where this is too strict for your needs, you can increase this limit.
